<?php

namespace ContainerJRdIKnT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BENcnHpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bENcnHp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bENcnHp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\DepartmentController::add' => ['privates', '.service_locator.nc_hMr7', 'get_ServiceLocator_NcHMr7Service', true],
            'App\\Controller\\EmailController::add' => ['privates', '.service_locator.nc_hMr7', 'get_ServiceLocator_NcHMr7Service', true],
            'App\\Controller\\EmployeeController::add' => ['privates', '.service_locator.nc_hMr7', 'get_ServiceLocator_NcHMr7Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\DepartmentController:add' => ['privates', '.service_locator.nc_hMr7', 'get_ServiceLocator_NcHMr7Service', true],
            'App\\Controller\\EmailController:add' => ['privates', '.service_locator.nc_hMr7', 'get_ServiceLocator_NcHMr7Service', true],
            'App\\Controller\\EmployeeController:add' => ['privates', '.service_locator.nc_hMr7', 'get_ServiceLocator_NcHMr7Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\DepartmentController::add' => '?',
            'App\\Controller\\EmailController::add' => '?',
            'App\\Controller\\EmployeeController::add' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\DepartmentController:add' => '?',
            'App\\Controller\\EmailController:add' => '?',
            'App\\Controller\\EmployeeController:add' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
