<?php

namespace ContainerMSdY84c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\EmailType' shared autowired service.
     *
     * @return \App\Form\EmailType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/EmailType.php';

        return $container->privates['App\\Form\\EmailType'] = new \App\Form\EmailType();
    }
}
