<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRL4wEoN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRL4wEoN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRL4wEoN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRL4wEoN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRL4wEoN\App_KernelDevDebugContainer([
    'container.build_hash' => 'RL4wEoN',
    'container.build_id' => 'cb5b2516',
    'container.build_time' => 1637214314,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRL4wEoN');
