<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJRdIKnT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJRdIKnT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJRdIKnT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJRdIKnT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJRdIKnT\App_KernelDevDebugContainer([
    'container.build_hash' => 'JRdIKnT',
    'container.build_id' => '50b0af29',
    'container.build_time' => 1637108337,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJRdIKnT');
