<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRDHCmFA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRDHCmFA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRDHCmFA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRDHCmFA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRDHCmFA\App_KernelDevDebugContainer([
    'container.build_hash' => 'RDHCmFA',
    'container.build_id' => '914303a3',
    'container.build_time' => 1637042212,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRDHCmFA');
